"""
JAX-based implementation of the BIO formulation 
for 2D Stokes squirmer in a confinement
"""

import jax

import jax.numpy as jnp
from jax import jit
from functools import partial
import sys, os
# Get the absolute path of the current script
current_dir = os.path.dirname(os.path.abspath(__file__))
# Construct the path to the folder containing the module you want to import
utils_path = os.path.join(current_dir, '..')
# Add the folder to the system path
sys.path.append(utils_path)
from Sto_kernel_utils_pytree import *

def pair_block(src, trg, same_body, mu, need_T=True):
    """
    SL+DL operator (and its traction) generated by a density on body `src` and
    evaluated on body `trg`.  `same_body` is a *Python* bool (block layout is static),
    so only one branch is ever traced.

    same_body=True  -- singular self-quadrature, no jump term added here.
                       (self-to-self DL traction vanishes, hence only the SL traction.)
    same_body=False -- close evaluation, exterior side, so that near-touching bodies
                       are still resolved.
    """
    if same_body:
        res_sl, _, res_slT = StoSLP(src, src, mu, jnp.array([]), self=True, near=False, panel=False, need_T=need_T)
        res_dl, _, _ = StoDLP(src, src, mu, jnp.array([]), self=True, near=False, panel=False, need_T=False)
        return res_sl + res_dl, (res_slT if need_T else None)
    res_sl, _, res_sl_T = stoSLP_closeglobal(trg, src, mu, jnp.eye(2*src['x'].size), 'e', need_T)
    res_dl, _, res_dl_T = stoDLP_closeglobal(trg, src, mu, jnp.eye(2*src['x'].size), 'e', need_T)
    return res_sl + res_dl, (res_sl_T + res_dl_T if need_T else None)

def body_grid(cell_j, cell_k, mu, need_T=True):
    """
    Assemble the (targets in cell_k) x (sources in cell_j) grid of body-body blocks.
    Rows follow the key order of cell_k, columns the key order of cell_j.
    Returns (velocity block, traction block).  No jump terms are included.
    """
    grid_u = []
    grid_T = []
    for key_k in cell_k.keys():
        row_u = []
        row_T = []
        for key_j in cell_j.keys():
            # Set-up of ptcl_cell and obs_cell makes sure keys won't overlap ('ptcl_1' vs 'obs_1', etc)
            u_block, T_block = pair_block(cell_j[key_j], cell_k[key_k], key_j == key_k, mu, need_T)
            row_u.append(u_block)
            if need_T:
                row_T.append(T_block)
        grid_u.append(row_u)
        if need_T:
            grid_T.append(row_T)
    return jnp.block(grid_u), (jnp.block(grid_T) if need_T else None)


@jit
def rbm_static_block(s, obs_cell, mu):
    """
    The wall(+obstacle) diagonal block of the confined RBM system.  Nothing here
    depends on the active particles, so in a time evolution where only the swimmers
    move this block -- and any factorization of it -- is built once and reused.

    Returns a dict holding the individual sub-blocks (so that the callers can paste
    them into the full operator without recomputing them) together with 'Eww', the
    assembled wall+obstacle diagonal block.  The obstacle sub-blocks are absent when
    obs_cell is empty.
    """
    Nsx = s['x'].size
    # Wall self-to-self
    [Asrcsum,_,_] = StoDLP(s, s, mu, jnp.array([]), self=True, near=False, panel=True, need_T=False)
    A11 = -jnp.eye(2*Nsx) / 2. + Asrcsum
    if not obs_cell:
        return {'A11': A11, 'Eww': A11}

    obs_keys = obs_cell.keys()
    # Obstacle to wall
    A12_obs = jnp.hstack([StoDLP(s, obs_cell[k], mu, jnp.array([]), self=False, near=True, panel=False, need_T=False)[0]
                          + StoSLP(s, obs_cell[k], mu, jnp.array([]), self=False, near=True, panel=False, need_T=False)[0]
                          for k in obs_keys])
    # Wall to obstacle (traction on obstacles is not needed)
    A21_obs = jnp.vstack([StoDLP(obs_cell[k], s, mu, jnp.array([]), self=False, near=True, panel=True, need_T=False)[0]
                          for k in obs_keys])
    # Obstacle to obstacle, with the exterior SL+DL jump
    A22_o2o, _ = body_grid(obs_cell, obs_cell, mu, need_T=False)
    A22_o2o = jnp.eye(A22_o2o.shape[0]) / 2. + A22_o2o

    Eww = jnp.block([[A11,     A12_obs],
                     [A21_obs, A22_o2o]])
    return {'A11': A11, 'A12_obs': A12_obs, 'A21_obs': A21_obs,
            'A22_o2o': A22_o2o, 'Eww': Eww}


@jit
def rbm_wrapper(s, obs_cell, ptcl_cell, mu, static=None):
    """
    `static` is an optional pre-built wall(+obstacle) block, exactly as returned by
    rbm_static_block(s, obs_cell, mu).  Nothing in it depends on the active particles,
    so a time evolution in which only the swimmers move should build it once and pass
    it back in on every later step instead of paying for it again.
    """
    if not obs_cell: # only active ptcl and channel
        E, A, intF, intT, blocks = rbm(s, ptcl_cell, mu, static)
    else:
        E, A, intF, intT, blocks = rbm_obs(s, obs_cell, ptcl_cell, mu, static)
    return E, A, intF, intT, blocks

@jit
def rbm(s, ptcl_cell, mu, static=None):
    """
    A DL formulation on wall (like before) and SL+DL on particle -- Rigid body motion
    Close-eval included in all non-self interactions.

    Returns E, bc_gamma_mat, intF, intT, blocks.  `blocks` is the same operator in
    2x2 block form, split into the static (wall) group W and the particle group P
    (particle densities plus the U/Omega unknowns, particle plus force/torque rows):
    E = [[Eww, Ewp], [Epw, Epp]].  See solve_schur.
    """
    Nsx = s['x'].size
    # Wall self-to-self -- reuse the caller's cached block when it supplied one.
    if static is None:
        static = rbm_static_block(s, {}, mu)
    A11 = static['Eww']
    # Particle to wall from all ptcls in ptcl_cell, summed
    ptcl_keys = ptcl_cell.keys()
    num_ptcl = len(ptcl_keys)
    A12_list = [StoDLP(s, ptcl_cell[k], mu, jnp.array([]), self=False, near=True, panel=False, need_T=False)[0] + StoSLP(s, ptcl_cell[k], mu,  jnp.array([]), self=False, near=True, panel=False, need_T=False)[0] for k in ptcl_keys]
    A12 = jnp.hstack(list(A12_list))
    # Wall to particle
    A21_tuples = [StoDLP(ptcl_cell[k], s, mu, jnp.array([]), self = False, near = True, panel = True) for k in ptcl_keys]
    A21_u_list, _, A21_T_list = zip(*A21_tuples)
    A21 = jnp.vstack(A21_u_list)
    A21_T = jnp.vstack(A21_T_list)

    # FROM ptcl_j (with near) to ptcl_k
    A22, T3 = body_grid(ptcl_cell, ptcl_cell, mu)
    A22 = jnp.eye(A22.shape[0]) / 2. + A22

    # Rigid body motion added to b.c.
    Nptx_total = sum(len(ptcl_cell[k]['x']) for k in ptcl_keys)
    bc_sqr = jnp.zeros((2 * Nptx_total, 3 * num_ptcl)) # just the ptcl BC part

    current_row_offset = 0
    F_blocks = []
    T_blocks = [] # store values now for force and torque integrals
    for i, k in enumerate(ptcl_keys):
        pt = ptcl_cell[k]  # Complex points: x + iy
        n_nodes = len(pt['x'])
        # X - Xc
        xc = jnp.mean(pt['x'])
        rel_pos = pt['x'] - xc
        dx = jnp.real(rel_pos)
        dy = jnp.imag(rel_pos)
        # Indices
        ptcl_x_rows = jnp.arange(current_row_offset, current_row_offset + n_nodes)
        ptcl_y_rows = jnp.arange(current_row_offset + n_nodes, current_row_offset + 2 * n_nodes)
        col_ux = 3 * i
        col_uy = 3 * i + 1
        col_omega = 3 * i + 2

        bc_sqr = bc_sqr.at[ptcl_x_rows, col_ux].set(-1.0)
        bc_sqr = bc_sqr.at[ptcl_y_rows, col_uy].set(-1.0)
        bc_sqr = bc_sqr.at[ptcl_x_rows, col_omega].set(-dy)
        bc_sqr = bc_sqr.at[ptcl_y_rows, col_omega].set(dx)

        w_row = pt['ws'][None, :] # shape (1, n_nodes)
        z_row = jnp.zeros_like(w_row)
        f_block = jnp.block([
            [w_row, z_row],
            [z_row, w_row]
        ])
        F_blocks.append(f_block)
        t_block = jnp.concatenate([(-dy * pt['ws'])[None, :], (dx * pt['ws'])[None, :]], axis=1)
        T_blocks.append(t_block)

        current_row_offset += 2 * n_nodes

    # Net force zero and net torque zero
    fMat_ptcl = - ( -jnp.eye(T3.shape[0])/2. + T3)
    fMat_wall = - A21_T

    intF_op = jax.scipy.linalg.block_diag(*F_blocks)
    intT_op = jax.scipy.linalg.block_diag(*T_blocks)

    # --- Block form: W = wall, P = ptcl densities + (U, Omega) ---
    n_stat = 2 * Nsx
    Ewp = jnp.hstack([A12, jnp.zeros((n_stat, 3 * num_ptcl))])
    Epw_u = A21                              # ptcl rows, wall columns
    Epp_u = jnp.hstack([A22, bc_sqr])        # ptcl rows, ptcl + rbm columns
    uom_F_zeros = jnp.zeros((2 * num_ptcl, 3 * num_ptcl))
    uom_T_zeros = jnp.zeros((num_ptcl, 3 * num_ptcl))
    intF_W = intF_op @ fMat_wall
    intT_W = intT_op @ fMat_wall
    intF_P = jnp.hstack([intF_op @ fMat_ptcl, uom_F_zeros])
    intT_P = jnp.hstack([intT_op @ fMat_ptcl, uom_T_zeros])
    Epw = jnp.vstack([Epw_u, intF_W, intT_W])
    Epp = jnp.vstack([Epp_u, intF_P, intT_P])
    blocks = {'Eww': A11, 'Ewp': Ewp, 'Epw': Epw, 'Epp': Epp}

    # --- Final assembly ---
    bc_gamma_mat = jnp.block([[A11,   Ewp  ],
                              [Epw_u, Epp_u]])
    intF = jnp.hstack([intF_W, intF_P])
    intT = jnp.hstack([intT_W, intT_P])
    E = jnp.block([[A11, Ewp],
                   [Epw, Epp]])

    return E, bc_gamma_mat, intF, intT, blocks

@jit
def rbm_obs(s, obs_cell, ptcl_cell, mu, static=None):
    """
    A DL formulation on wall (like before)
     SL+DL formulation on obstacles (passive and often fixed particle) 
     and SL+DL on active particle with Rigid body motion
    Close-eval included in all non-self interactions.

    Returns E, bc_gamma_mat, intF, intT, blocks.  `blocks` is the same operator in
    2x2 block form, split into the static (wall + obstacle) group W and the particle
    group P (particle densities plus the U/Omega unknowns, particle plus force/torque
    rows): E = [[Eww, Ewp], [Epw, Epp]].  Only Eww is free of active-particle
    geometry, so it is the piece worth caching across time steps.  See solve_schur.
    """
    Nsx = s['x'].size
    # Wall self-to-self, obstacle self-to-self and the wall<->obstacle coupling --
    # reuse the caller's cached block when it supplied one.
    if static is None:
        static = rbm_static_block(s, obs_cell, mu)
    A11 = static['A11']
    A12_obs = static['A12_obs']
    A21_obs = static['A21_obs']
    A22_o2o = static['A22_o2o']
    obs_keys = obs_cell.keys()
    # Particle to wall from all ptcls in ptcl_cell, summed
    ptcl_keys = ptcl_cell.keys()
    num_ptcl = len(ptcl_keys)
    A12_ptcl = jnp.hstack([StoDLP(s, ptcl_cell[k], mu, jnp.array([]), self=False, near=True, panel=False, need_T=False)[0]
                           + StoSLP(s, ptcl_cell[k], mu, jnp.array([]), self=False, near=True, panel=False, need_T=False)[0]
                           for k in ptcl_keys])
    # Wall to particle
    A21_ptcl_tuples = [StoDLP(ptcl_cell[k], s, mu, jnp.array([]), self=False, near=True, panel=True) for k in ptcl_keys]
    A21_ptcl_u_list, _, A21_ptcl_T_list = zip(*A21_ptcl_tuples)
    A21_ptcl = jnp.vstack(A21_ptcl_u_list)
    A21_T = jnp.vstack(A21_ptcl_T_list)

    # Body-body couplings involving the active particles
    A22_p2p, T_p2p = body_grid(ptcl_cell, ptcl_cell, mu)
    A22_p2p = jnp.eye(A22_p2p.shape[0]) / 2. + A22_p2p
    A22_p2o, _ = body_grid(ptcl_cell, obs_cell, mu, need_T=False)
    A22_o2p, T_o2p = body_grid(obs_cell, ptcl_cell, mu)

    # Rigid body motion added to b.c.
    Nptx_total = sum(len(ptcl_cell[k]['x']) for k in ptcl_keys)
    Nobsx_total = sum(len(obs_cell[k]['x']) for k in obs_keys)
    bc_sqr = jnp.zeros((2 * Nptx_total, 3 * num_ptcl)) # just the ptcl BC part

    current_row_offset = 0
    F_blocks = []
    T_blocks = [] # store values now for force and torque integrals
    for i, k in enumerate(ptcl_keys):
        pt = ptcl_cell[k]  # Complex points: x + iy
        n_nodes = len(pt['x'])
        # X - Xc
        xc = jnp.mean(pt['x'])
        rel_pos = pt['x'] - xc
        dx = jnp.real(rel_pos)
        dy = jnp.imag(rel_pos)
        # Indices
        ptcl_x_rows = jnp.arange(current_row_offset, current_row_offset + n_nodes)
        ptcl_y_rows = jnp.arange(current_row_offset + n_nodes, current_row_offset + 2 * n_nodes)
        col_ux = 3 * i
        col_uy = 3 * i + 1
        col_omega = 3 * i + 2

        bc_sqr = bc_sqr.at[ptcl_x_rows, col_ux].set(-1.0)
        bc_sqr = bc_sqr.at[ptcl_y_rows, col_uy].set(-1.0)
        bc_sqr = bc_sqr.at[ptcl_x_rows, col_omega].set(-dy)
        bc_sqr = bc_sqr.at[ptcl_y_rows, col_omega].set(dx)

        w_row = pt['ws'][None, :] # shape (1, n_nodes)
        z_row = jnp.zeros_like(w_row)
        f_block = jnp.block([
            [w_row, z_row],
            [z_row, w_row]
        ])
        F_blocks.append(f_block)
        t_block = jnp.concatenate([(-dy * pt['ws'])[None, :], (dx * pt['ws'])[None, :]], axis=1)
        T_blocks.append(t_block)

        current_row_offset += 2 * n_nodes

    # Net force zero and net torque zero
    T_p2p = -jnp.eye(T_p2p.shape[0])/2. + T_p2p # active particle self-to-self SL traction jump
    fMat_wall = - A21_T
    fMat_obs = - T_o2p
    fMat_ptcl = - T_p2p

    intF_op = jax.scipy.linalg.block_diag(*F_blocks)
    intT_op = jax.scipy.linalg.block_diag(*T_blocks)

    # --- Block form: W = wall + obstacles, P = ptcl densities + (U, Omega) ---
    n_stat = 2 * Nsx + 2 * Nobsx_total
    Eww = static['Eww']
    Ewp = jnp.hstack([jnp.vstack([A12_ptcl, A22_p2o]), jnp.zeros((n_stat, 3 * num_ptcl))])
    Epw_u = jnp.hstack([A21_ptcl, A22_o2p])       # ptcl rows, wall + obs columns
    Epp_u = jnp.hstack([A22_p2p, bc_sqr])         # ptcl rows, ptcl + rbm columns
    fMat_W = jnp.hstack([fMat_wall, fMat_obs])
    uom_F_zeros = jnp.zeros((2 * num_ptcl, 3 * num_ptcl))
    uom_T_zeros = jnp.zeros((num_ptcl, 3 * num_ptcl))
    intF_W = intF_op @ fMat_W
    intT_W = intT_op @ fMat_W
    intF_P = jnp.hstack([intF_op @ fMat_ptcl, uom_F_zeros])
    intT_P = jnp.hstack([intT_op @ fMat_ptcl, uom_T_zeros])
    Epw = jnp.vstack([Epw_u, intF_W, intT_W])
    Epp = jnp.vstack([Epp_u, intF_P, intT_P])
    blocks = {'Eww': Eww, 'Ewp': Ewp, 'Epw': Epw, 'Epp': Epp}

    # --- Final assembly ---
    bc_gamma_mat = jnp.block([[Eww,   Ewp  ],
                              [Epw_u, Epp_u]])
    intF = jnp.hstack([intF_W, intF_P])
    intT = jnp.hstack([intT_W, intT_P])
    E = jnp.block([[Eww, Ewp],
                   [Epw, Epp]])

    return E, bc_gamma_mat, intF, intT, blocks




@jit
def evalsol_all(t, s, obs_cell, ptcl_cell, mu, edens):
    N_wall = s['x'].size
    N_obs_tot = sum([obs['x'].size for obs in obs_cell.values()])
    N_ptcl_tot = sum([ptcl['x'].size for ptcl in ptcl_cell.values()])
    wall_dens = edens[:2*N_wall]
    obs_dens = edens[2*N_wall:2*(N_wall+N_obs_tot)]
    ptcl_dens = edens[2*(N_wall+N_obs_tot):2*(N_wall+N_obs_tot+N_ptcl_tot)]

    # wall and proxy to target
    [u, p, _] = StoDLP(t, s, mu, wall_dens, self=False, near=True, panel=True)
    # u = u @ wall_dens
    # p = p @ wall_dens

    # TODO: use vmap when number of particles increase dramatically.
    # Obstacle to target
    current_offset = 0
    if obs_cell:
        for obs in obs_cell.values():
            num_dof = obs['x'].size * 2 
            this_obs_dens = obs_dens[current_offset : current_offset + num_dof]
            [uSo, pSo, _] = StoSLP(t, obs, mu, this_obs_dens, self=False, near=True, panel=False, need_T = False)
            [uDo, pDo, _] = StoDLP(t, obs, mu, this_obs_dens, self=False, near=True, panel=False, need_T = False)
            # u = u + (uSo + uDo) @ this_obs_dens
            # p = p + (pSo + pDo) @ this_obs_dens
            u = u + (uSo + uDo)
            p = p + (pSo + pDo)
            current_offset += num_dof
    # Swimmers to target
    current_offset = 0
    if ptcl_cell:
        for pt in ptcl_cell.values():
            num_dof = pt['x'].size * 2 
            this_ptcl_dens = ptcl_dens[current_offset : current_offset + num_dof]
            [uSp, pSp, _] = StoSLP(t, pt, mu, this_ptcl_dens, self=False, near=True, panel=False, need_T = False)
            [uDp, pDp, _] = StoDLP(t, pt, mu, this_ptcl_dens, self=False, near=True, panel=False, need_T = False)
            # u = u + (uSp + uDp) @ this_ptcl_dens
            # p = p + (pSp + pDp) @ this_ptcl_dens
            u = u + (uSp + uDp)
            p = p + (pSp + pDp)
            current_offset += num_dof

    if len(u.shape) > 1 and u.shape[1] == 1:
        u = u.ravel()
        p = p.ravel()
    
    return u,p

# =============================================================================
#  Solvers for the extended RBM system
#
#  Three interchangeable ways of getting the densities and (U, Omega) out of the
#  system built above.  They all take the same right-hand side and return
#  (solution, residual norm), so they can be swapped freely:
#
#    solve_dense_lstsq   least squares, the historical default
#    solve_dense_direct  jnp.linalg.solve -- E is square, so this is legal
#    solve_schur         block elimination of the static (wall + obstacle) group
#
#  solve_schur is the one aimed at time evolution: only the swimmers move, so
#  Eww is identical at every step and its factorization can be built once with
#  factor_static_block and handed back in on every subsequent solve.  The
#  coupling blocks Ewp/Epw/Epp still have to be rebuilt each step because they
#  depend on the swimmer positions.
# =============================================================================

def solve_dense_lstsq(E, rhs, rcond=1e-15):
    """Mode 1: least-squares solve of the full extended system."""
    x = jnp.linalg.lstsq(E, rhs, rcond=rcond)[0]
    return x, jnp.linalg.norm(E @ x - rhs)


def solve_dense_direct(E, rhs):
    """Mode 2: direct square solve of the full extended system."""
    x = jnp.linalg.solve(E, rhs)
    return x, jnp.linalg.norm(E @ x - rhs)


def factor_static_block(Eww, method='pinv', rcond=1e-12):
    """
    Factor the static wall(+obstacle) block for reuse across time steps.

    'pinv' (default) -- dense pseudo-inverse.  The interior-Dirichlet DL wall
    operator -I/2 + D carries the classical rank-one normal-vector nullspace and
    no completion term is added here, so a plain LU of Eww is near-singular.  That
    nullspace generates zero velocity, so dropping it is physically harmless.
    'lu' -- LU factorization, cheaper, use when Eww is known to be well conditioned.
    """
    if method == 'pinv':
        return {'method': 'pinv', 'op': jnp.linalg.pinv(Eww, rcond=rcond)}
    elif method == 'lu':
        return {'method': 'lu', 'op': jax.scipy.linalg.lu_factor(Eww)}
    raise ValueError(f"unknown static factorization method '{method}'")


def apply_static_inverse(fac, B):
    """Apply the factorization from factor_static_block to a vector or matrix."""
    if fac['method'] == 'pinv':
        return fac['op'] @ B
    return jax.scipy.linalg.lu_solve(fac['op'], B)


def solve_schur(blocks, rhs, static_fac=None, method='pinv', rcond=1e-15):
    """
    Mode 3: solve E x = rhs by eliminating the static group.

    With E = [[Eww, Ewp], [Epw, Epp]] and rhs = [b_w; b_p],

        x_w = Eww^-1 (b_w - Ewp x_p),   (Epp - Epw Eww^-1 Ewp) x_p = b_p - Epw Eww^-1 b_w

    `blocks` is the dict returned by rbm / rbm_obs / rbm_wrapper; the split point is
    read off Eww, so no slicing of E is needed (E need not be formed at all).

    Pass `static_fac` from a previous call to skip refactoring Eww -- that is the
    point of the whole exercise for time stepping.  Returns (x, resid, static_fac).
    """
    Eww = blocks['Eww']; Ewp = blocks['Ewp']
    Epw = blocks['Epw']; Epp = blocks['Epp']
    n_stat = Eww.shape[0]
    b_w = rhs[:n_stat]
    b_p = rhs[n_stat:]

    if static_fac is None:
        static_fac = factor_static_block(Eww, method=method)

    X = apply_static_inverse(static_fac, Ewp)   # Eww^-1 Ewp
    y = apply_static_inverse(static_fac, b_w)   # Eww^-1 b_w

    S = Epp - Epw @ X
    x_p = jnp.linalg.lstsq(S, b_p - Epw @ y, rcond=rcond)[0]
    x_w = y - X @ x_p
    x = jnp.concatenate([x_w, x_p])

    resid = jnp.linalg.norm(jnp.concatenate([Eww @ x_w + Ewp @ x_p - b_w,
                                             Epw @ x_w + Epp @ x_p - b_p]))
    return x, resid, static_fac


def solve_rbm_system(E, blocks, rhs, mode=1, static_fac=None, rcond=1e-15):
    """
    Dispatch on the solver mode: 1 = lstsq, 2 = direct solve, 3 = Schur complement.
    Returns (x, resid, static_fac); static_fac is None except in mode 3.
    """
    if mode == 1:
        x, resid = solve_dense_lstsq(E, rhs, rcond=rcond)
        return x, resid, None
    elif mode == 2:
        x, resid = solve_dense_direct(E, rhs)
        return x, resid, None
    elif mode == 3:
        return solve_schur(blocks, rhs, static_fac=static_fac, rcond=rcond)
    raise ValueError(f"unknown solver mode {mode}, expected 1, 2 or 3")
