"""
JAX-based implementation of the BIO formulation 
for 2D Stokes squirmer in a confinement
"""

import jax

import jax.numpy as jnp
from jax import jit
from functools import partial
from typing import Any
import sys, os
# Get the absolute path of the current script
current_dir = os.path.dirname(os.path.abspath(__file__))
# Construct the path to the folder containing the module you want to import
utils_path = os.path.join(current_dir, '..')
# Add the folder to the system path
sys.path.append(utils_path)
from Sto_kernel_utils_pytree import *
import numpy as np
import scipy.sparse.linalg as spla
import scipy.linalg as sla

def pair_block(src, trg, same_body, mu, need_T=True, split=None):
    """
    SL+DL operator (and its traction) generated by a density on body `src` and
    evaluated on body `trg`.  `same_body` is a *Python* bool (block layout is static),
    so only one branch is ever traced.

    same_body=True  -- singular self-quadrature, no jump term added here.
                       (self-to-self DL traction vanishes, hence only the SL traction.)
    same_body=False -- close evaluation, exterior side, so that near-touching bodies
                       are still resolved.

    `split`, when given for an off-diagonal pair, is the (near rows, far rows, inverse
    permutation) triple over `trg`'s nodes returned by _partition: the near target rows
    get the close evaluation above, the far rows get the plain smooth rule (accurate to
    roundoff outside the boundary layer, one matmul), and the two are stitched back into
    `trg`'s node order.  `split=None` reproduces the all-close behaviour exactly, so a
    caller that passes nothing is bit-identical to before this argument existed.  The
    diagonal (same_body) block is always the self quadrature and ignores `split`.
    """
    if same_body:
        res_sl, _, res_slT = StoSLP(src, src, mu, jnp.array([]), self=True, near=False, panel=False, need_T=need_T)
        res_dl, _, _ = StoDLP(src, src, mu, jnp.array([]), self=True, near=False, panel=False, need_T=False)
        return res_sl + res_dl, (res_slT if need_T else None)
    if split is None:
        res_sl, _, res_sl_T = stoSLP_closeglobal(trg, src, mu, jnp.eye(2*src['x'].size), 'e', need_T)
        res_dl, _, res_dl_T = stoDLP_closeglobal(trg, src, mu, jnp.eye(2*src['x'].size), 'e', need_T)
        return res_sl + res_dl, (res_sl_T + res_dl_T if need_T else None)
    return _pair_block_split(src, trg, mu, need_T, split)


def _pair_block_split(src, trg, mu, need_T, split):
    """Matrix pair_block with `trg`'s near rows close-evaluated and its far rows smooth.

    Reuses _rows/_reassemble from the near/far field evaluator: those operate on axis 0,
    so the same permutation that stitches a (2M,) stacked field back together stitches a
    (2M, 2Nsrc) operator block -- and its traction block -- back together unchanged.
    """
    near_rows, far_rows, inverse = split
    n_near = near_rows.shape[0]
    n_far = far_rows.shape[0]
    eye = jnp.eye(2 * src['x'].size)

    u_near = T_near = u_far = T_far = None
    if n_near:
        tn = _rows(trg, near_rows)
        sl, _, slT = stoSLP_closeglobal(tn, src, mu, eye, 'e', need_T)
        dl, _, dlT = stoDLP_closeglobal(tn, src, mu, eye, 'e', need_T)
        u_near = sl + dl
        T_near = (slT + dlT) if need_T else None
    if n_far:
        tf = _rows(trg, far_rows)
        sl, _, slT = StoSLP(tf, src, mu, jnp.array([]), self=False, near=False, panel=False, need_T=need_T)
        dl, _, dlT = StoDLP(tf, src, mu, jnp.array([]), self=False, near=False, panel=False, need_T=need_T)
        u_far = sl + dl
        T_far = (slT + dlT) if need_T else None

    u = _reassemble(u_near, u_far, inverse, n_near, n_far)
    T = _reassemble(T_near, T_far, inverse, n_near, n_far) if need_T else None
    return u, T


def wall_body_block(trg, s, mu, split=None, need_T=True):
    """Interior double-layer of the wall source `s` evaluated on body `trg` (the
    wall->swimmer block A21): velocity operator and its traction.

    With `split=None` this is the all-close panel rule at every target row, bit-identical
    to `StoDLP(trg, s, ..., near=True, panel=True)`.  When a (near rows, far rows, inverse)
    triple is supplied, the near target rows keep the panel close evaluation and the far
    rows -- swimmer nodes well inside the domain, away from the wall curve -- take the
    plain smooth rule, stitched back into `trg`'s node order.  Same axis-0 reassembly the
    body-body `_pair_block_split` uses, so it applies to the (2M, 2N) operator and its
    traction block unchanged.
    """
    if split is None:
        u, _, T = StoDLP(trg, s, mu, jnp.array([]), self=False, near=True, panel=True,
                         need_T=need_T)
        return u, (T if need_T else None)
    near_rows, far_rows, inverse = split
    n_near = near_rows.shape[0]
    n_far = far_rows.shape[0]

    u_near = T_near = u_far = T_far = None
    if n_near:
        tn = _rows(trg, near_rows)
        u_near, _, T_near = StoDLP(tn, s, mu, jnp.array([]), self=False, near=True,
                                   panel=True, need_T=need_T)
    if n_far:
        tf = _rows(trg, far_rows)
        u_far, _, T_far = StoDLP(tf, s, mu, jnp.array([]), self=False, near=False,
                                 panel=False, need_T=need_T)

    u = _reassemble(u_near, u_far, inverse, n_near, n_far)
    T = _reassemble(T_near, T_far, inverse, n_near, n_far) if need_T else None
    return u, T


def body_grid(cell_j, cell_k, mu, need_T=True, split=None):
    """
    Assemble the (targets in cell_k) x (sources in cell_j) grid of body-body blocks.
    Rows follow the key order of cell_k, columns the key order of cell_j.
    Returns (velocity block, traction block).  No jump terms are included.

    `split`, when given, is a dict keyed by (source key, target key) whose values are the
    per-pair near/far triples (or None) that pair_block consumes; the diagonal pairs are
    always self quadrature and are never looked up.  `split=None` leaves every off-diagonal
    block on the all-close path, bit-identical to before.
    """
    grid_u = []
    grid_T = []
    for key_k in cell_k.keys():
        row_u = []
        row_T = []
        for key_j in cell_j.keys():
            # Set-up of ptcl_cell and obs_cell makes sure keys won't overlap ('ptcl_1' vs 'obs_1', etc)
            pair_split = None if (split is None or key_j == key_k) else split.get((key_j, key_k))
            u_block, T_block = pair_block(cell_j[key_j], cell_k[key_k], key_j == key_k, mu, need_T,
                                          split=pair_split)
            row_u.append(u_block)
            if need_T:
                row_T.append(T_block)
        grid_u.append(row_u)
        if need_T:
            grid_T.append(row_T)
    return jnp.block(grid_u), (jnp.block(grid_T) if need_T else None)


@jit
def rbm_static_block(s, obs_cell, mu, split=None):
    """
    The wall(+obstacle) diagonal block of the confined RBM system.  Nothing here
    depends on the active particles, so in a time evolution where only the swimmers
    move this block -- and any factorization of it -- is built once and reused.

    Returns a dict holding the individual sub-blocks (so that the callers can paste
    them into the full operator without recomputing them) together with 'Eww', the
    assembled wall+obstacle diagonal block.  The obstacle sub-blocks are absent when
    obs_cell is empty.
    """
    Nsx = s['x'].size
    # Wall self-to-self
    [Asrcsum,_,_] = StoDLP(s, s, mu, jnp.array([]), self=True, near=False, panel=True, need_T=False)
    A11 = -jnp.eye(2*Nsx) / 2. + Asrcsum
    if not obs_cell:
        return {'A11': A11, 'Eww': A11}

    obs_keys = obs_cell.keys()
    # Obstacle to wall
    A12_obs = jnp.hstack([StoDLP(s, obs_cell[k], mu, jnp.array([]), self=False, near=True, panel=False, need_T=False)[0]
                          + StoSLP(s, obs_cell[k], mu, jnp.array([]), self=False, near=True, panel=False, need_T=False)[0]
                          for k in obs_keys])
    # Wall to obstacle (traction on obstacles is not needed)
    A21_obs = jnp.vstack([StoDLP(obs_cell[k], s, mu, jnp.array([]), self=False, near=True, panel=True, need_T=False)[0]
                          for k in obs_keys])
    # Obstacle to obstacle, with the exterior SL+DL jump.  Most obstacle pairs are far
    # apart, so this is where near/far masking earns the most: a supplied `split` sends
    # each far pair through the smooth rule instead of a full close-eval pass.
    A22_o2o, _ = body_grid(obs_cell, obs_cell, mu, need_T=False, split=split)
    A22_o2o = jnp.eye(A22_o2o.shape[0]) / 2. + A22_o2o

    Eww = jnp.block([[A11,     A12_obs],
                     [A21_obs, A22_o2o]])
    return {'A11': A11, 'A12_obs': A12_obs, 'A21_obs': A21_obs,
            'A22_o2o': A22_o2o, 'Eww': Eww}


@jit
def rbm_wrapper(s, obs_cell, ptcl_cell, mu, static=None, split=None):
    """
    `static` is an optional pre-built wall(+obstacle) block, exactly as returned by
    rbm_static_block(s, obs_cell, mu).  Nothing in it depends on the active particles,
    so a time evolution in which only the swimmers move should build it once and pass
    it back in on every later step instead of paying for it again.

    `split` is an optional near/far split of the body-body couplings, keyed by
    (source key, target key); see nearfar_split_E.  `split=None` builds every coupling
    with close evaluation, exactly as before.
    """
    if not obs_cell: # only active ptcl and channel
        E, A, intF, intT, blocks = rbm(s, ptcl_cell, mu, static, split=split)
    else:
        E, A, intF, intT, blocks = rbm_obs(s, obs_cell, ptcl_cell, mu, static, split=split)
    return E, A, intF, intT, blocks

@jit
def rbm(s, ptcl_cell, mu, static=None, split=None):
    """
    A DL formulation on wall (like before) and SL+DL on particle -- Rigid body motion
    Close-eval included in all non-self interactions.

    Returns E, bc_gamma_mat, intF, intT, blocks.  `blocks` is the same operator in
    2x2 block form, split into the static (wall) group W and the particle group P
    (particle densities plus the U/Omega unknowns, particle plus force/torque rows):
    E = [[Eww, Ewp], [Epw, Epp]].  See solve_schur.
    """
    Nsx = s['x'].size
    # Wall self-to-self -- reuse the caller's cached block when it supplied one.
    if static is None:
        static = rbm_static_block(s, {}, mu, split=split)
    A11 = static['Eww']
    # Particle to wall from all ptcls in ptcl_cell, summed
    ptcl_keys = ptcl_cell.keys()
    num_ptcl = len(ptcl_keys)
    # Particle -> wall is the swimmer's global close eval at the wall's nodes: identical
    # in shape to a body-body pair (source ptcl, target wall), so pair_block gates it.
    A12_list = [pair_block(ptcl_cell[k], s, False, mu, need_T=False,
                           split=(None if split is None else split.get((k, 'wall'))))[0]
                for k in ptcl_keys]
    A12 = jnp.hstack(list(A12_list))
    # Wall to particle
    A21_tuples = [wall_body_block(ptcl_cell[k], s, mu,
                                  split=(None if split is None else split.get(('wall', k))))
                  for k in ptcl_keys]
    A21_u_list, A21_T_list = zip(*A21_tuples)
    A21 = jnp.vstack(A21_u_list)
    A21_T = jnp.vstack(A21_T_list)

    # FROM ptcl_j (with near) to ptcl_k
    A22, T3 = body_grid(ptcl_cell, ptcl_cell, mu, split=split)
    A22 = jnp.eye(A22.shape[0]) / 2. + A22

    # Rigid body motion added to b.c.
    Nptx_total = sum(len(ptcl_cell[k]['x']) for k in ptcl_keys)
    bc_sqr = jnp.zeros((2 * Nptx_total, 3 * num_ptcl)) # just the ptcl BC part

    current_row_offset = 0
    F_blocks = []
    T_blocks = [] # store values now for force and torque integrals
    for i, k in enumerate(ptcl_keys):
        pt = ptcl_cell[k]  # Complex points: x + iy
        n_nodes = len(pt['x'])
        # X - Xc
        xc = jnp.mean(pt['x'])
        rel_pos = pt['x'] - xc
        dx = jnp.real(rel_pos)
        dy = jnp.imag(rel_pos)
        # Indices
        ptcl_x_rows = jnp.arange(current_row_offset, current_row_offset + n_nodes)
        ptcl_y_rows = jnp.arange(current_row_offset + n_nodes, current_row_offset + 2 * n_nodes)
        col_ux = 3 * i
        col_uy = 3 * i + 1
        col_omega = 3 * i + 2

        bc_sqr = bc_sqr.at[ptcl_x_rows, col_ux].set(-1.0)
        bc_sqr = bc_sqr.at[ptcl_y_rows, col_uy].set(-1.0)
        bc_sqr = bc_sqr.at[ptcl_x_rows, col_omega].set(-dy)
        bc_sqr = bc_sqr.at[ptcl_y_rows, col_omega].set(dx)

        w_row = pt['ws'][None, :] # shape (1, n_nodes)
        z_row = jnp.zeros_like(w_row)
        f_block = jnp.block([
            [w_row, z_row],
            [z_row, w_row]
        ])
        F_blocks.append(f_block)
        t_block = jnp.concatenate([(-dy * pt['ws'])[None, :], (dx * pt['ws'])[None, :]], axis=1)
        T_blocks.append(t_block)

        current_row_offset += 2 * n_nodes

    # Net force zero and net torque zero
    fMat_ptcl = - ( -jnp.eye(T3.shape[0])/2. + T3)
    fMat_wall = - A21_T

    intF_op = jax.scipy.linalg.block_diag(*F_blocks)
    intT_op = jax.scipy.linalg.block_diag(*T_blocks)

    # --- Block form: W = wall, P = ptcl densities + (U, Omega) ---
    n_stat = 2 * Nsx
    Ewp = jnp.hstack([A12, jnp.zeros((n_stat, 3 * num_ptcl))])
    Epw_u = A21                              # ptcl rows, wall columns
    Epp_u = jnp.hstack([A22, bc_sqr])        # ptcl rows, ptcl + rbm columns
    uom_F_zeros = jnp.zeros((2 * num_ptcl, 3 * num_ptcl))
    uom_T_zeros = jnp.zeros((num_ptcl, 3 * num_ptcl))
    intF_W = intF_op @ fMat_wall
    intT_W = intT_op @ fMat_wall
    intF_P = jnp.hstack([intF_op @ fMat_ptcl, uom_F_zeros])
    intT_P = jnp.hstack([intT_op @ fMat_ptcl, uom_T_zeros])
    Epw = jnp.vstack([Epw_u, intF_W, intT_W])
    Epp = jnp.vstack([Epp_u, intF_P, intT_P])
    blocks = {'Eww': A11, 'Ewp': Ewp, 'Epw': Epw, 'Epp': Epp}

    # --- Final assembly ---
    bc_gamma_mat = jnp.block([[A11,   Ewp  ],
                              [Epw_u, Epp_u]])
    intF = jnp.hstack([intF_W, intF_P])
    intT = jnp.hstack([intT_W, intT_P])
    E = jnp.block([[A11, Ewp],
                   [Epw, Epp]])

    return E, bc_gamma_mat, intF, intT, blocks

@jit
def rbm_obs(s, obs_cell, ptcl_cell, mu, static=None, split=None):
    """
    A DL formulation on wall (like before)
     SL+DL formulation on obstacles (passive and often fixed particle) 
     and SL+DL on active particle with Rigid body motion
    Close-eval included in all non-self interactions.

    Returns E, bc_gamma_mat, intF, intT, blocks.  `blocks` is the same operator in
    2x2 block form, split into the static (wall + obstacle) group W and the particle
    group P (particle densities plus the U/Omega unknowns, particle plus force/torque
    rows): E = [[Eww, Ewp], [Epw, Epp]].  Only Eww is free of active-particle
    geometry, so it is the piece worth caching across time steps.  See solve_schur.
    """
    Nsx = s['x'].size
    # Wall self-to-self, obstacle self-to-self and the wall<->obstacle coupling --
    # reuse the caller's cached block when it supplied one.
    if static is None:
        static = rbm_static_block(s, obs_cell, mu, split=split)
    A11 = static['A11']
    A12_obs = static['A12_obs']
    A21_obs = static['A21_obs']
    A22_o2o = static['A22_o2o']
    obs_keys = obs_cell.keys()
    # Particle to wall from all ptcls in ptcl_cell, summed
    ptcl_keys = ptcl_cell.keys()
    num_ptcl = len(ptcl_keys)
    A12_ptcl = jnp.hstack([pair_block(ptcl_cell[k], s, False, mu, need_T=False,
                                      split=(None if split is None else split.get((k, 'wall'))))[0]
                           for k in ptcl_keys])
    # Wall to particle
    A21_ptcl_tuples = [wall_body_block(ptcl_cell[k], s, mu,
                                       split=(None if split is None else split.get(('wall', k))))
                       for k in ptcl_keys]
    A21_ptcl_u_list, A21_ptcl_T_list = zip(*A21_ptcl_tuples)
    A21_ptcl = jnp.vstack(A21_ptcl_u_list)
    A21_T = jnp.vstack(A21_ptcl_T_list)

    # Body-body couplings involving the active particles
    A22_p2p, T_p2p = body_grid(ptcl_cell, ptcl_cell, mu, split=split)
    A22_p2p = jnp.eye(A22_p2p.shape[0]) / 2. + A22_p2p
    A22_p2o, _ = body_grid(ptcl_cell, obs_cell, mu, need_T=False, split=split)
    A22_o2p, T_o2p = body_grid(obs_cell, ptcl_cell, mu, split=split)

    # Rigid body motion added to b.c.
    Nptx_total = sum(len(ptcl_cell[k]['x']) for k in ptcl_keys)
    Nobsx_total = sum(len(obs_cell[k]['x']) for k in obs_keys)
    bc_sqr = jnp.zeros((2 * Nptx_total, 3 * num_ptcl)) # just the ptcl BC part

    current_row_offset = 0
    F_blocks = []
    T_blocks = [] # store values now for force and torque integrals
    for i, k in enumerate(ptcl_keys):
        pt = ptcl_cell[k]  # Complex points: x + iy
        n_nodes = len(pt['x'])
        # X - Xc
        xc = jnp.mean(pt['x'])
        rel_pos = pt['x'] - xc
        dx = jnp.real(rel_pos)
        dy = jnp.imag(rel_pos)
        # Indices
        ptcl_x_rows = jnp.arange(current_row_offset, current_row_offset + n_nodes)
        ptcl_y_rows = jnp.arange(current_row_offset + n_nodes, current_row_offset + 2 * n_nodes)
        col_ux = 3 * i
        col_uy = 3 * i + 1
        col_omega = 3 * i + 2

        bc_sqr = bc_sqr.at[ptcl_x_rows, col_ux].set(-1.0)
        bc_sqr = bc_sqr.at[ptcl_y_rows, col_uy].set(-1.0)
        bc_sqr = bc_sqr.at[ptcl_x_rows, col_omega].set(-dy)
        bc_sqr = bc_sqr.at[ptcl_y_rows, col_omega].set(dx)

        w_row = pt['ws'][None, :] # shape (1, n_nodes)
        z_row = jnp.zeros_like(w_row)
        f_block = jnp.block([
            [w_row, z_row],
            [z_row, w_row]
        ])
        F_blocks.append(f_block)
        t_block = jnp.concatenate([(-dy * pt['ws'])[None, :], (dx * pt['ws'])[None, :]], axis=1)
        T_blocks.append(t_block)

        current_row_offset += 2 * n_nodes

    # Net force zero and net torque zero
    T_p2p = -jnp.eye(T_p2p.shape[0])/2. + T_p2p # active particle self-to-self SL traction jump
    fMat_wall = - A21_T
    fMat_obs = - T_o2p
    fMat_ptcl = - T_p2p

    intF_op = jax.scipy.linalg.block_diag(*F_blocks)
    intT_op = jax.scipy.linalg.block_diag(*T_blocks)

    # --- Block form: W = wall + obstacles, P = ptcl densities + (U, Omega) ---
    n_stat = 2 * Nsx + 2 * Nobsx_total
    Eww = static['Eww']
    Ewp = jnp.hstack([jnp.vstack([A12_ptcl, A22_p2o]), jnp.zeros((n_stat, 3 * num_ptcl))])
    Epw_u = jnp.hstack([A21_ptcl, A22_o2p])       # ptcl rows, wall + obs columns
    Epp_u = jnp.hstack([A22_p2p, bc_sqr])         # ptcl rows, ptcl + rbm columns
    fMat_W = jnp.hstack([fMat_wall, fMat_obs])
    uom_F_zeros = jnp.zeros((2 * num_ptcl, 3 * num_ptcl))
    uom_T_zeros = jnp.zeros((num_ptcl, 3 * num_ptcl))
    intF_W = intF_op @ fMat_W
    intT_W = intT_op @ fMat_W
    intF_P = jnp.hstack([intF_op @ fMat_ptcl, uom_F_zeros])
    intT_P = jnp.hstack([intT_op @ fMat_ptcl, uom_T_zeros])
    Epw = jnp.vstack([Epw_u, intF_W, intT_W])
    Epp = jnp.vstack([Epp_u, intF_P, intT_P])
    blocks = {'Eww': Eww, 'Ewp': Ewp, 'Epw': Epw, 'Epp': Epp}

    # --- Final assembly ---
    bc_gamma_mat = jnp.block([[Eww,   Ewp  ],
                              [Epw_u, Epp_u]])
    intF = jnp.hstack([intF_W, intF_P])
    intT = jnp.hstack([intT_W, intT_P])
    E = jnp.block([[Eww, Ewp],
                   [Epw, Epp]])

    return E, bc_gamma_mat, intF, intT, blocks


# =============================================================================
#  Matrix-free (matvec) form of the same confined RBM operator
#
#  Everything below applies exactly the operator that rbm / rbm_obs assemble, one
#  vector at a time, so that E never has to be formed.  Every term is a
#  term-by-term mirror of the dense assembly above -- when one changes, so must
#  the other, and test_nonperi_rbm.py checks matvec(v) == E @ v to enforce it.
#
#  Two shape conventions have to be respected here.  With a 1-D density the *self*
#  quadrature path (StoSLPmat / StoDLPmat) returns a 1-D (2M,) array, but every
#  close-eval path (stoSLP_closeglobal, stoDLP_closeglobal, stoDLP_closepanel)
#  returns a 2-D (2M, 1) column.  Mixing the two broadcasts silently into a matrix,
#  so every kernel result is jnp.ravel()-ed at the point of use.  Second, traction
#  is only needed where the *target* is an active particle (it feeds the force and
#  torque rows); everywhere else need_T=False keeps the close-eval kernels from
#  doing their O(M*N^2) traction work.
# =============================================================================

def rbm_dof_layout(s, obs_cell, ptcl_cell):
    """
    Offsets and sizes of the extended unknown vector, in exactly the order the dense
    E uses:

        [ wall dens (2*Nw) | obs dens (2*Nobs) | ptcl dens (2*Nptcl) | UOmega (3*n_ptcl) ]

    and, for the residual, the matching row order

        [ wall vel | obs vel | ptcl vel | F (2*n_ptcl) | torque (n_ptcl) ].

    Key insertion order of obs_cell / ptcl_cell defines the sub-block order, the same
    contract body_grid relies on.
    """
    n_wall = 2 * s['x'].size
    obs_sizes = [(k, 2 * obs_cell[k]['x'].size) for k in obs_cell]
    ptcl_sizes = [(k, 2 * ptcl_cell[k]['x'].size) for k in ptcl_cell]
    n_obs = sum(n for _, n in obs_sizes)
    n_ptcl = sum(n for _, n in ptcl_sizes)
    n_uom = 3 * len(ptcl_sizes)
    return {'n_wall': n_wall, 'n_obs': n_obs, 'n_ptcl': n_ptcl, 'n_uom': n_uom,
            'obs_sizes': obs_sizes, 'ptcl_sizes': ptcl_sizes,
            'off_obs': n_wall, 'off_ptcl': n_wall + n_obs,
            'off_uom': n_wall + n_obs + n_ptcl,
            'n_total': n_wall + n_obs + n_ptcl + n_uom}


def unpack_rbm_vector(x, s, obs_cell, ptcl_cell):
    """Split a flat unknown vector into (s_dens, obs_dens_cell, ptcl_dens_cell, UOmega)."""
    lay = rbm_dof_layout(s, obs_cell, ptcl_cell)
    s_dens = x[:lay['n_wall']]
    off = lay['off_obs']
    obs_dens_cell = {}
    for k, n in lay['obs_sizes']:
        obs_dens_cell[k] = x[off:off + n]
        off += n
    ptcl_dens_cell = {}
    for k, n in lay['ptcl_sizes']:
        ptcl_dens_cell[k] = x[off:off + n]
        off += n
    return s_dens, obs_dens_cell, ptcl_dens_cell, x[off:off + lay['n_uom']]


def pack_rbm_residual(s_vel, obs_vel, ptcl_vel, F, torque):
    """Glue the matvec outputs back into E's row order."""
    return jnp.concatenate([s_vel, obs_vel, ptcl_vel, F, torque])


def pair_block_matvec(src, trg, src_dens, same_body, mu, need_T=True, split=None):
    """
    Matvec counterpart of pair_block: the SL+DL velocity (and traction) that
    `src_dens` on body `src` generates on body `trg`.  `same_body` is a Python bool,
    so only one branch is ever traced.  Returns 1-D (2*Ntrg,) arrays; the traction
    slot is None when need_T is False.

    `split` is the same near/far triple pair_block takes, and the far branch here goes
    through the identical smooth kernel it does there -- so masked matvec stays equal to
    masked E @ v to the same close-eval traction floor the unmasked pair does.
    `split=None` reproduces the all-close apply exactly.
    """
    if same_body:
        res_sl, _, res_slT = StoSLP(src, src, mu, src_dens, self=True, near=False, panel=False, need_T=need_T)
        # self-to-self DL traction vanishes, so it is never asked for here
        res_dl, _, _ = StoDLP(src, src, mu, src_dens, self=True, near=False, panel=False, need_T=False)
        u = jnp.ravel(res_sl) + jnp.ravel(res_dl)
        return u, (jnp.ravel(res_slT) if need_T else None)
    if split is None:
        res_sl, _, res_sl_T = stoSLP_closeglobal(trg, src, mu, src_dens, 'e', need_T)
        res_dl, _, res_dl_T = stoDLP_closeglobal(trg, src, mu, src_dens, 'e', need_T)
        u = jnp.ravel(res_sl) + jnp.ravel(res_dl)
        return u, (jnp.ravel(res_sl_T) + jnp.ravel(res_dl_T) if need_T else None)
    return _pair_block_matvec_split(src, trg, src_dens, mu, need_T, split)


def _pair_block_matvec_split(src, trg, src_dens, mu, need_T, split):
    """Matvec pair_block with `trg`'s near rows close-evaluated and its far rows smooth."""
    near_rows, far_rows, inverse = split
    n_near = near_rows.shape[0]
    n_far = far_rows.shape[0]

    u_near = T_near = u_far = T_far = None
    if n_near:
        tn = _rows(trg, near_rows)
        sl, _, slT = stoSLP_closeglobal(tn, src, mu, src_dens, 'e', need_T)
        dl, _, dlT = stoDLP_closeglobal(tn, src, mu, src_dens, 'e', need_T)
        u_near = jnp.ravel(sl) + jnp.ravel(dl)
        T_near = (jnp.ravel(slT) + jnp.ravel(dlT)) if need_T else None
    if n_far:
        tf = _rows(trg, far_rows)
        sl, _, slT = StoSLP(tf, src, mu, src_dens, self=False, near=False, panel=False, need_T=need_T)
        dl, _, dlT = StoDLP(tf, src, mu, src_dens, self=False, near=False, panel=False, need_T=need_T)
        u_far = jnp.ravel(sl) + jnp.ravel(dl)
        T_far = (jnp.ravel(slT) + jnp.ravel(dlT)) if need_T else None

    u = _reassemble(u_near, u_far, inverse, n_near, n_far)
    T = _reassemble(T_near, T_far, inverse, n_near, n_far) if need_T else None
    return u, T


def wall_body_matvec(trg, s, src_dens, mu, split=None, need_T=True):
    """Matvec counterpart of wall_body_block: the interior DL velocity (and traction)
    that the wall density `src_dens` generates on body `trg`.  Returns 1-D (2*Ntrg,)
    arrays; the far branch is the same smooth kernel wall_body_block uses, so masked
    matvec stays equal to masked E @ v.  `split=None` reproduces the all-close apply.
    """
    if split is None:
        u, _, T = StoDLP(trg, s, mu, src_dens, self=False, near=True, panel=True,
                         need_T=need_T)
        return jnp.ravel(u), (jnp.ravel(T) if need_T else None)
    near_rows, far_rows, inverse = split
    n_near = near_rows.shape[0]
    n_far = far_rows.shape[0]

    u_near = T_near = u_far = T_far = None
    if n_near:
        tn = _rows(trg, near_rows)
        u, _, T = StoDLP(tn, s, mu, src_dens, self=False, near=True, panel=True,
                         need_T=need_T)
        u_near = jnp.ravel(u)
        T_near = jnp.ravel(T) if need_T else None
    if n_far:
        tf = _rows(trg, far_rows)
        u, _, T = StoDLP(tf, s, mu, src_dens, self=False, near=False, panel=False,
                         need_T=need_T)
        u_far = jnp.ravel(u)
        T_far = jnp.ravel(T) if need_T else None

    u = _reassemble(u_near, u_far, inverse, n_near, n_far)
    T = _reassemble(T_near, T_far, inverse, n_near, n_far) if need_T else None
    return u, T


def body_grid_matvec(cell_j, cell_k, dens_j, mu, need_T=True, split=None):
    """
    Matvec counterpart of body_grid: for every target body in cell_k, sum the
    contributions of every source body in cell_j, then concatenate over cell_k in key
    order.  `dens_j` is keyed by the *source* cell.  No jump terms are included.

    `split` is the (source key, target key) -> triple dict body_grid takes; the same
    near/far masking is applied here so the matrix-free apply mirrors the assembled E.
    """
    n_k = sum(2 * cell_k[k]['x'].size for k in cell_k)
    if not cell_j or not cell_k:
        zeros = jnp.zeros((n_k,))
        return zeros, (zeros if need_T else None)
    u_all = []
    T_all = []
    for key_k in cell_k.keys():
        u_k = None
        T_k = None
        for key_j in cell_j.keys():
            # Set-up of ptcl_cell and obs_cell makes sure keys won't overlap ('ptcl_1' vs 'obs_1', etc)
            pair_split = None if (split is None or key_j == key_k) else split.get((key_j, key_k))
            u_b, T_b = pair_block_matvec(cell_j[key_j], cell_k[key_k], dens_j[key_j],
                                         key_j == key_k, mu, need_T, split=pair_split)
            u_k = u_b if u_k is None else u_k + u_b
            if need_T:
                T_k = T_b if T_k is None else T_k + T_b
        u_all.append(u_k)
        if need_T:
            T_all.append(T_k)
    return jnp.concatenate(u_all), (jnp.concatenate(T_all) if need_T else None)


def _ptcl_rbm_and_loads(ptcl_cell, ptcl_dens_flat, UOmega, trac_static, T_p2p):
    """
    The two per-particle pieces of the matvec that involve no kernel evaluation.

    1. The rigid-body-motion term.  In the dense assembly this is the bc_sqr block of
       U/Omega columns, whose action on [Ux, Uy, Omega] is  -U - Omega x (x - xc).
    2. The net-force / net-torque rows, which integrate the *total* traction on each
       particle against ws and (-dy, dx) * ws.  Mirroring the dense
       fMat_ptcl = -(-I/2 + T3) and fMat_W = -A21_T, the total traction is
       -(trac_static + (-ptcl_dens/2 + T_p2p)).

    `trac_static` is the traction the static group (wall, plus obstacles when
    present) generates on the particles; `T_p2p` is the particle-particle traction
    without its -1/2 SL jump.  All three inputs use the particle stacking: bodies
    contiguous in ptcl_cell key order, x-components then y-components within a body.

    Returns (bc_sqr, F, torque) with F ordered [Fx_1, Fy_1, Fx_2, Fy_2, ...].
    """
    trac_total = -(trac_static + (-ptcl_dens_flat / 2. + T_p2p))

    bc_parts = []
    F_parts = []
    torque_parts = []
    off = 0
    for i, k in enumerate(ptcl_cell.keys()):
        pt = ptcl_cell[k]
        n = pt['x'].size
        rel_pos = pt['x'] - jnp.mean(pt['x'])   # x - xc
        dx = jnp.real(rel_pos)
        dy = jnp.imag(rel_pos)

        Ux, Uy, Om = UOmega[3 * i], UOmega[3 * i + 1], UOmega[3 * i + 2]
        bc_parts.append(jnp.concatenate([-Ux - Om * dy, -Uy + Om * dx]))

        trac_x = trac_total[off:off + n]
        trac_y = trac_total[off + n:off + 2 * n]
        F_parts.append(jnp.stack([jnp.dot(pt['ws'], trac_x), jnp.dot(pt['ws'], trac_y)]))
        torque_parts.append(jnp.dot(-dy * pt['ws'], trac_x) + jnp.dot(dx * pt['ws'], trac_y))
        off += 2 * n

    if not F_parts:
        empty = jnp.zeros((0,))
        return empty, empty, empty
    return (jnp.concatenate(bc_parts), jnp.concatenate(F_parts),
            jnp.stack(torque_parts))


@jit
def rbm_matvec_wrapper(s, obs_cell, ptcl_cell, s_dens, obs_dens_cell, ptcl_dens_cell, UOmega, mu,
                       split=None):
    """
    Apply the confined RBM operator to one set of densities plus (U, Omega).
    Returns (s_vel, obs_vel, ptcl_vel, F, torque); obs_vel is empty when there are no
    obstacles.  Dispatch mirrors rbm_wrapper.  `split` masks the body-body couplings
    exactly as the dense side does, so matvec == E @ v holds masked or not.
    """
    if not obs_cell: # only active ptcl and channel
        return rbm_matvec(s, ptcl_cell, s_dens, ptcl_dens_cell, UOmega, mu, split=split)
    return rbm_matvec_obs(s, obs_cell, ptcl_cell, s_dens, obs_dens_cell, ptcl_dens_cell, UOmega, mu,
                          split=split)


@jit
def rbm_matvec(s, ptcl_cell, s_dens, ptcl_dens_cell, UOmega, mu, split=None):
    """
    Matrix-free apply of the operator that `rbm` assembles: interior DL on the wall,
    exterior SL+DL on each active particle, close evaluation on every non-self
    interaction, extended by the force-free / torque-free rows.
    """
    ptcl_keys = list(ptcl_cell.keys())

    # --- Wall rows: the -I/2 + D self block, plus SL+DL from every particle ---
    s_vel = -s_dens / 2. + jnp.ravel(
        StoDLP(s, s, mu, s_dens, self=True, near=False, panel=True, need_T=False)[0])
    for k in ptcl_keys:
        u_wall, _ = pair_block_matvec(ptcl_cell[k], s, ptcl_dens_cell[k], False, mu,
                                      need_T=False,
                                      split=(None if split is None else split.get((k, 'wall'))))
        s_vel = s_vel + u_wall

    # --- Wall to particle; its traction feeds the force/torque rows ---
    A21_u = []
    A21_T = []
    for k in ptcl_keys:
        u_k, T_k = wall_body_matvec(ptcl_cell[k], s, s_dens, mu, need_T=True,
                                    split=(None if split is None else split.get(('wall', k))))
        A21_u.append(u_k)
        A21_T.append(T_k)
    ptcl_vel = jnp.concatenate(A21_u)
    trac_static = jnp.concatenate(A21_T)

    # --- FROM ptcl_j (with near) to ptcl_k, with the exterior SL+DL jump ---
    u_p2p, T_p2p = body_grid_matvec(ptcl_cell, ptcl_cell, ptcl_dens_cell, mu, need_T=True, split=split)
    ptcl_dens_flat = jnp.concatenate([ptcl_dens_cell[k] for k in ptcl_keys])
    ptcl_vel = ptcl_vel + ptcl_dens_flat / 2. + u_p2p

    # --- Rigid body motion in the b.c., and the net force / net torque rows ---
    bc_sqr, F, torque = _ptcl_rbm_and_loads(ptcl_cell, ptcl_dens_flat, UOmega, trac_static, T_p2p)

    return s_vel, jnp.zeros((0,)), ptcl_vel + bc_sqr, F, torque


@jit
def rbm_matvec_obs(s, obs_cell, ptcl_cell, s_dens, obs_dens_cell, ptcl_dens_cell, UOmega, mu,
                   split=None):
    """
    Matrix-free apply of the operator that `rbm_obs` assembles: interior DL on the
    wall, exterior SL+DL on the passive obstacles and on the active particles, close
    evaluation on every non-self interaction, extended by the force-free /
    torque-free rows.
    """
    obs_keys = list(obs_cell.keys())
    ptcl_keys = list(ptcl_cell.keys())

    # --- Wall rows: -I/2 + D self block, plus SL+DL from every obstacle and particle ---
    s_vel = -s_dens / 2. + jnp.ravel(
        StoDLP(s, s, mu, s_dens, self=True, near=False, panel=True, need_T=False)[0])
    # Obstacle -> wall stays all-close, matching the cached static block on the dense side.
    for k in obs_cell.keys():
        d = obs_dens_cell[k]
        s_vel = s_vel \
            + jnp.ravel(StoDLP(s, obs_cell[k], mu, d, self=False, near=True, panel=False, need_T=False)[0]) \
            + jnp.ravel(StoSLP(s, obs_cell[k], mu, d, self=False, near=True, panel=False, need_T=False)[0])
    # Swimmer -> wall is masked: most wall nodes are far from the compact swimmer.
    for k in ptcl_keys:
        u_wall, _ = pair_block_matvec(ptcl_cell[k], s, ptcl_dens_cell[k], False, mu,
                                      need_T=False,
                                      split=(None if split is None else split.get((k, 'wall'))))
        s_vel = s_vel + u_wall

    # --- Obstacle rows: wall to obstacle, obstacle self group with jump, particles to obstacle ---
    obs_vel = jnp.concatenate([
        jnp.ravel(StoDLP(obs_cell[k], s, mu, s_dens, self=False, near=True, panel=True, need_T=False)[0])
        for k in obs_keys])
    obs_dens_flat = jnp.concatenate([obs_dens_cell[k] for k in obs_keys])
    u_o2o, _ = body_grid_matvec(obs_cell, obs_cell, obs_dens_cell, mu, need_T=False, split=split)
    u_p2o, _ = body_grid_matvec(ptcl_cell, obs_cell, ptcl_dens_cell, mu, need_T=False, split=split)
    obs_vel = obs_vel + obs_dens_flat / 2. + u_o2o + u_p2o

    # --- Wall to particle; its traction feeds the force/torque rows ---
    A21_u = []
    A21_T = []
    for k in ptcl_keys:
        u_k, T_k = wall_body_matvec(ptcl_cell[k], s, s_dens, mu, need_T=True,
                                    split=(None if split is None else split.get(('wall', k))))
        A21_u.append(u_k)
        A21_T.append(T_k)
    ptcl_vel = jnp.concatenate(A21_u)

    # --- Body-body couplings involving the active particles ---
    u_o2p, T_o2p = body_grid_matvec(obs_cell, ptcl_cell, obs_dens_cell, mu, need_T=True, split=split)
    u_p2p, T_p2p = body_grid_matvec(ptcl_cell, ptcl_cell, ptcl_dens_cell, mu, need_T=True, split=split)
    ptcl_dens_flat = jnp.concatenate([ptcl_dens_cell[k] for k in ptcl_keys])
    ptcl_vel = ptcl_vel + u_o2p + ptcl_dens_flat / 2. + u_p2p

    # The static group here is wall + obstacles, matching fMat_W = [fMat_wall, fMat_obs]
    trac_static = jnp.concatenate(A21_T) + T_o2p

    # --- Rigid body motion in the b.c., and the net force / net torque rows ---
    bc_sqr, F, torque = _ptcl_rbm_and_loads(ptcl_cell, ptcl_dens_flat, UOmega, trac_static, T_p2p)

    return s_vel, obs_vel, ptcl_vel + bc_sqr, F, torque


@jit
def rbm_matvec_flat(x, s, obs_cell, ptcl_cell, mu, split=None):
    """
    The whole operator as a flat vector -> flat vector map, equal to E @ x for the E
    that rbm_wrapper assembles (with the same `split`, if any).  This is the single
    jitted entry point that the scipy LinearOperator below wraps.
    """
    s_dens, obs_dens_cell, ptcl_dens_cell, UOmega = unpack_rbm_vector(x, s, obs_cell, ptcl_cell)
    s_vel, obs_vel, ptcl_vel, F, torque = rbm_matvec_wrapper(
        s, obs_cell, ptcl_cell, s_dens, obs_dens_cell, ptcl_dens_cell, UOmega, mu, split=split)
    return pack_rbm_residual(s_vel, obs_vel, ptcl_vel, F, torque)


@jit
def evalsol_all(t, s, obs_cell, ptcl_cell, mu, edens):
    N_wall = s['x'].size
    N_obs_tot = sum([obs['x'].size for obs in obs_cell.values()])
    N_ptcl_tot = sum([ptcl['x'].size for ptcl in ptcl_cell.values()])
    wall_dens = edens[:2*N_wall]
    obs_dens = edens[2*N_wall:2*(N_wall+N_obs_tot)]
    ptcl_dens = edens[2*(N_wall+N_obs_tot):2*(N_wall+N_obs_tot+N_ptcl_tot)]

    # wall and proxy to target
    [u, p, _] = StoDLP(t, s, mu, wall_dens, self=False, near=True, panel=True)
    # u = u @ wall_dens
    # p = p @ wall_dens

    # TODO: use vmap when number of particles increase dramatically.
    # Obstacle to target
    current_offset = 0
    if obs_cell:
        for obs in obs_cell.values():
            num_dof = obs['x'].size * 2 
            this_obs_dens = obs_dens[current_offset : current_offset + num_dof]
            [uSo, pSo, _] = StoSLP(t, obs, mu, this_obs_dens, self=False, near=True, panel=False, need_T = False)
            [uDo, pDo, _] = StoDLP(t, obs, mu, this_obs_dens, self=False, near=True, panel=False, need_T = False)
            # u = u + (uSo + uDo) @ this_obs_dens
            # p = p + (pSo + pDo) @ this_obs_dens
            u = u + (uSo + uDo)
            p = p + (pSo + pDo)
            current_offset += num_dof
    # Swimmers to target
    current_offset = 0
    if ptcl_cell:
        for pt in ptcl_cell.values():
            num_dof = pt['x'].size * 2 
            this_ptcl_dens = ptcl_dens[current_offset : current_offset + num_dof]
            [uSp, pSp, _] = StoSLP(t, pt, mu, this_ptcl_dens, self=False, near=True, panel=False, need_T = False)
            [uDp, pDp, _] = StoDLP(t, pt, mu, this_ptcl_dens, self=False, near=True, panel=False, need_T = False)
            # u = u + (uSp + uDp) @ this_ptcl_dens
            # p = p + (pSp + pDp) @ this_ptcl_dens
            u = u + (uSp + uDp)
            p = p + (pSp + pDp)
            current_offset += num_dof

    if len(u.shape) > 1 and u.shape[1] == 1:
        u = u.ravel()
        p = p.ravel()

    return u,p


# =============================================================================
#  Near/far-gated field evaluation
#
#  evalsol_all sends every target through the close-evaluation rule of every
#  body: a twelve-body geometry runs twelve compensated-quadrature passes over
#  the whole grid.  That rule is only *needed* inside a boundary layer a few
#  source node spacings thick; outside it the plain smooth quadrature -- one
#  matmul -- is accurate to roundoff.  evalsol_nearfar splits the targets on
#  that criterion, body by body, and sends each branch only the rows it is
#  responsible for.  Passing a split whose every body is `None` (all targets
#  near) reproduces evalsol_all exactly; the host-side classifier body_near_mask
#  and the padded partition _partition build the split off concrete geometry.
#
#  The jitted evaluator keeps every shape pose-independent so it compiles once:
#  the target set is never filtered, and each body's near/far index arrays have
#  a fixed length (the swimmer's near array padded to a capacity bound read off
#  the geometry).  See tests/test_fieldeval.py in the forward package for the
#  properties this pins, and BENCHMARKS.md for the boundary-layer sweep.
# =============================================================================

# Distance, in *local* source node spacings, beyond which the periodic trapezoid
# rule is taken as converged.  Its error decays like exp(-2*pi*d/h) on a curve
# it resolves, so six spacings is exp(-37.7) ~ 4e-17 -- roundoff -- but the
# constant is measured, not assumed.  It is the one knob that trades accuracy for
# a thinner boundary layer, and the layer is what the saving is made of.
GLOBAL_NEAR_FACTOR = 6.0

# The panel rule brings its own criterion: stoDLP_closepanel switches to close
# evaluation when the sum of the distances from the target to a panel's two
# endpoints falls below twice the panel length.  Reusing it verbatim is what
# makes the split exact on a panel wall.
PANEL_NEAR_FACTOR = 2.0


def _as_complex_targets(points_xy):
    points = np.asarray(points_xy, dtype=float)
    if points.ndim != 2 or points.shape[1] != 2:
        raise ValueError(f"points_xy must have shape (n,2), got {points.shape}")
    return points[:, 0] + 1j * points[:, 1]


def body_near_mask(targets, body, *, factor=GLOBAL_NEAR_FACTOR,
                   panel_factor=PANEL_NEAR_FACTOR):
    """Which targets need ``body``'s close-evaluation rule.

    Host side and in numpy: the targets and every body are concrete at the call
    site, so the classification never enters a traced graph and never becomes a
    shape jax has to compile against.
    """

    nodes = np.asarray(body["x"])
    weights = np.real(np.asarray(body["ws"]))
    if "xlo" in body:
        lo = np.asarray(body["xlo"])
        hi = np.asarray(body["xhi"])
        order = nodes.size // lo.size
        panel_length = weights.reshape(lo.size, order).sum(axis=1)
        reach = np.abs(targets[:, None] - lo[None, :]) + np.abs(
            targets[:, None] - hi[None, :]
        )
        return np.any(reach < panel_factor * panel_length[None, :], axis=1)

    # Distance to each node in units of *that node's* spacing.  A mean spacing
    # will not do: the container is parametrised so that its nodes crowd into
    # the corners and thin out along the flat sides, and an obstacle ellipse
    # spreads them by its axis ratio, so the boundary layer the trapezoid rule
    # needs is several times thicker in some places than in others.  Scoring
    # every node by its own weight follows that variation.
    near = np.min(
        np.abs(targets[:, None] - nodes[None, :]) / weights[None, :], axis=1
    ) < factor
    if "a" in body and "radius" in body:
        # A closed body's deep interior is far from every node but must not be
        # left to the smooth rule, whose kernel is singular across the curve.
        # Those rows are discarded by the caller, so only their finiteness
        # matters -- but a stray inf in a matmul is worth not producing.
        near |= np.abs(targets - complex(np.asarray(body["a"]))) <= float(
            body["radius"]
        )
    return near


def _flat(array):
    """Drop the trailing singleton axis the close-eval kernels carry."""

    return array.ravel() if array.ndim > 1 and array.shape[1] == 1 else array


def _rows(t, index):
    return {"x": t["x"][index], "nx": t["nx"][index]}


def _reassemble(near, far, inverse, n_near, n_far):
    """Undo the near/far permutation of a ``(2M,)`` stacked field."""

    if n_far == 0:
        return jnp.concatenate([near[:n_near][inverse], near[n_near:][inverse]])
    if n_near == 0:
        return jnp.concatenate([far[:n_far][inverse], far[n_far:][inverse]])
    top = jnp.concatenate([near[:n_near], far[:n_far]])[inverse]
    bottom = jnp.concatenate([near[n_near:], far[n_far:]])[inverse]
    return jnp.concatenate([top, bottom])


def _reassemble_scalar(near, far, inverse, n_near, n_far):
    if n_far == 0:
        return near[inverse]
    if n_near == 0:
        return far[inverse]
    return jnp.concatenate([near, far])[inverse]


def smooth_field(t, s, mu, dens, *, wall=False):
    """Smooth-quadrature velocity and pressure, density folded in.

    The same rule as ``StoSLP``/``StoDLP`` with ``near=False`` and to the same
    roundoff -- ``tests/test_fieldeval.py`` pins that -- but computed in one
    pass instead of four.  The kernel path builds each of the single- and
    double-layer velocity and pressure *matrices* in full, ``(2M, 2N)`` apiece
    with a stack of ``(M, N)`` temporaries behind them, and only then contracts
    against one density vector.  At the far end of a near/far split that matrix
    is the whole cost, and it is memory, not arithmetic: the geometry it is
    built from (``r``, ``1/|r|^2``, the two components of ``r``) is shared by
    all four and gets rebuilt each time.  Forming it once and contracting the
    density in as it goes is worth about 2x.

    ``wall=True`` returns the double layer alone, which is the container's
    contribution; otherwise it is the exterior single plus double layer.
    """

    n = s["x"].size
    flat = dens.ndim == 1
    columns = dens[:, None] if flat else dens
    weights = s["ws"][:, None]
    w1 = weights * columns[:n]
    w2 = weights * columns[n:]

    r = t["x"][:, None] - s["x"][None, :]
    d1, d2 = jnp.real(r), jnp.imag(r)
    rr = d1 * d1 + d2 * d2
    irr = 1.0 / rr
    ny1 = jnp.real(s["nx"])[None, :]
    ny2 = jnp.imag(s["nx"])[None, :]

    # Double layer.
    rdotnir4 = (d1 * ny1 + d2 * ny2) * irr * irr
    cross = d1 * d2 * rdotnir4
    u1 = (1.0 / jnp.pi) * ((d1 * d1 * rdotnir4) @ w1 + cross @ w2)
    u2 = (1.0 / jnp.pi) * (cross @ w1 + (d2 * d2 * rdotnir4) @ w2)
    p = (mu / jnp.pi) * (
        (-ny1 * irr + 2.0 * rdotnir4 * d1) @ w1
        + (-ny2 * irr + 2.0 * rdotnir4 * d2) @ w2
    )

    if not wall:
        # Single layer, on the geometry already formed above.
        c = 1.0 / (4.0 * jnp.pi * mu)
        logir = -0.5 * jnp.log(rr)
        dd = d1 * d2 * irr
        u1 = u1 + c * ((logir + d1 * d1 * irr) @ w1 + dd @ w2)
        u2 = u2 + c * (dd @ w1 + (logir + d2 * d2 * irr) @ w2)
        p = p + (1.0 / (2.0 * jnp.pi)) * ((d1 * irr) @ w1 + (d2 * irr) @ w2)

    u = jnp.concatenate([u1, u2])
    return (u.ravel(), p.ravel()) if flat else (u, p)


def _close_field(t, body, mu, dens, *, wall):
    """The close-evaluation rule at every target -- what ``evalsol_all`` does."""

    if wall:
        u, p, _ = StoDLP(t, body, mu, dens, False, True, True, False)
        return _flat(u), _flat(p)
    uS, pS, _ = StoSLP(t, body, mu, dens, False, True, False, False)
    uD, pD, _ = StoDLP(t, body, mu, dens, False, True, False, False)
    return _flat(uS) + _flat(uD), _flat(pS) + _flat(pD)


def _split_field(t, body, mu, dens, split, *, wall):
    """Close evaluation on the near rows, smooth quadrature on the far rows.

    ``wall=True`` selects the interior double-layer alone, which is what the
    container contributes; a body contributes the exterior single plus double
    layer.  ``need_T=False`` throughout -- the field evaluator discards the
    traction, and in the close-eval kernels it is the largest single piece of
    work there is.

    ``split is None`` means every target is near this body, which is the usual
    verdict on a container wall: its nodes are spread over a curve as large as
    the domain, so the boundary layer the compensated rule is needed in swallows
    the interior.
    """

    if split is None:
        return _close_field(t, body, mu, dens, wall=wall)

    near_rows, far_rows, inverse = split
    n_near = near_rows.shape[0]
    n_far = far_rows.shape[0]

    u_near = p_near = u_far = p_far = None
    if n_near:
        tn = _rows(t, near_rows)
        if wall:
            uD, pD, _ = StoDLP(tn, body, mu, dens, False, True, True, False)
            u_near, p_near = _flat(uD), _flat(pD)
        else:
            uS, pS, _ = StoSLP(tn, body, mu, dens, False, True, False, False)
            uD, pD, _ = StoDLP(tn, body, mu, dens, False, True, False, False)
            u_near, p_near = _flat(uS) + _flat(uD), _flat(pS) + _flat(pD)
    if n_far:
        u_far, p_far = smooth_field(_rows(t, far_rows), body, mu, dens, wall=wall)

    u = _reassemble(u_near, u_far, inverse, n_near, n_far)
    p = _reassemble_scalar(p_near, p_far, inverse, n_near, n_far)
    return u, p


@jit
def evalsol_nearfar(t, s, obs_cell, ptcl_cell, mu, edens, split):
    """``evalsol_all`` with each body's close-eval rule confined to its near rows.

    Same arguments and same return as ``evalsol_all``, plus ``split``: one
    (near rows, far rows, inverse permutation) triple per body, keyed ``"wall"``
    and by the obstacle/particle keys, or None for a body every target is near.
    """

    n_wall = s["x"].size
    n_obs = sum(obs["x"].size for obs in obs_cell.values())
    n_ptcl = sum(ptcl["x"].size for ptcl in ptcl_cell.values())
    wall_dens = edens[: 2 * n_wall]
    obs_dens = edens[2 * n_wall : 2 * (n_wall + n_obs)]
    ptcl_dens = edens[2 * (n_wall + n_obs) : 2 * (n_wall + n_obs + n_ptcl)]

    u, p = _split_field(t, s, mu, wall_dens, split["wall"], wall=True)

    for cell, dens in ((obs_cell, obs_dens), (ptcl_cell, ptcl_dens)):
        offset = 0
        for key, body in cell.items():
            width = body["x"].size * 2
            du, dp = _split_field(
                t, body, mu, dens[offset : offset + width], split[key], wall=False
            )
            u = u + du
            p = p + dp
            offset += width

    return u, p


def grid_spacing(points_xy):
    """``(dx, dy)`` if the targets are a full uniform Cartesian grid, else None.

    Used only to bound the swimmer's near count.  A cloud that is not a grid
    gets no bound and falls back to close-evaluating the swimmer everywhere,
    which is correct and is what evalsol_all does.
    """

    points = np.asarray(points_xy, dtype=float)
    xs = np.unique(points[:, 0])
    ys = np.unique(points[:, 1])
    if xs.size < 2 or ys.size < 2 or xs.size * ys.size != points.shape[0]:
        return None
    dx, dy = np.diff(xs), np.diff(ys)
    if not (np.allclose(dx, dx[0]) and np.allclose(dy, dy[0])):
        return None
    return float(dx[0]), float(dy[0])


def _partition(near_mask, capacity):
    """Near/far row partition with the near half padded out to ``capacity``.

    The padding is taken from the *far* rows, so the two arrays still cover
    every target exactly once and the padded rows are close-evaluated instead
    of smoothly evaluated -- the more accurate of the two, never the less.
    """

    near = np.flatnonzero(near_mask).astype(np.int32)
    far = np.flatnonzero(~near_mask).astype(np.int32)
    short = int(capacity) - near.size
    if short > 0:
        near = np.concatenate([near, far[:short]])
        far = far[short:]
    order = np.concatenate([near, far])
    inverse = np.argsort(order).astype(np.int32)
    return near, far, inverse


def nearfar_split_E(s, obs_cell, ptcl_cell, *, factor=GLOBAL_NEAR_FACTOR,
                    panel_factor=PANEL_NEAR_FACTOR):
    """Near/far split of E's body-body couplings, for the `split=` of rbm_wrapper etc.

    The same idea evalsol_nearfar applies to the field targets, applied instead to the
    *other body's nodes* that a source couples into: for every ordered pair of distinct
    obstacle/particle bodies it classifies the target body's nodes against the source
    with body_near_mask, so a well-separated pair is sent through the smooth rule and a
    near-touching pair keeps close evaluation.  The result is keyed by
    (source key, target key) -- exactly what body_grid / body_grid_matvec look up -- with
    None wherever every target row is near (that block stays all-close, at no cost).

    The swimmer<->wall coupling is included under the key ``'wall'``.  The swimmer->wall
    block (A12: the wall's nodes are the targets of the swimmer's global close eval) is
    where it pays -- the wall is a curve as large as the domain, so most of its nodes sit
    far outside the compact swimmer's boundary layer, exactly as an obstacle's nodes do,
    and the smooth rule is accurate to roundoff there.  The reverse wall->swimmer block
    (A21) is usually all-near, because the swimmer lies inside the wall's interior layer;
    but when it is well separated -- a swimmer adrift in an empty container -- that block
    is sent smooth too, which is what the empty-geometry benchmark measures.  The
    obstacle<->wall blocks are left out: they live in the cached static block, where the
    coupling is paid once per geometry rather than once per swimmer pose.

    Splits are exact (capacity = number of near rows, no padding): correct for a fixed
    geometry, which is what the single-pose correctness tests and the timing benchmark
    use.  A time loop that keeps one compiled assembly across swimmer poses would pad the
    particle-involving pairs to a capacity bound, the way NearFarField pads the swimmer's
    grid split; that is a mechanical extension of this builder, not needed here.
    """
    bodies = {**obs_cell, **ptcl_cell}
    split = {}
    for trg_key, trg in bodies.items():
        targets = np.asarray(trg['x'])
        for src_key, src in bodies.items():
            if src_key == trg_key:
                continue
            split[(src_key, trg_key)] = _pair_split_or_none(
                targets, src, factor, panel_factor)

    # Swimmer <-> wall.  The wall is both a source (A21, panel close eval, targets are
    # the swimmer nodes) and a target (A12, the swimmer's global close eval, targets are
    # the wall nodes).  Keyed by 'wall' at whichever end the wall sits.
    wall_targets = np.asarray(s['x'])
    for ptcl_key, ptcl in ptcl_cell.items():
        split[(ptcl_key, 'wall')] = _pair_split_or_none(
            wall_targets, ptcl, factor, panel_factor)          # A12: swimmer -> wall
        split[('wall', ptcl_key)] = _pair_split_or_none(
            np.asarray(ptcl['x']), s, factor, panel_factor)    # A21: wall -> swimmer
    return split


def _pair_split_or_none(targets, src, factor, panel_factor):
    """Classify `targets` against source `src` and return the (near, far, inverse)
    partition, or None when every target row is near (that block stays all-close)."""
    mask = body_near_mask(targets, src, factor=factor, panel_factor=panel_factor)
    capacity = int(mask.sum())
    if capacity >= targets.size:
        return None
    return tuple(jnp.asarray(part) for part in _partition(mask, capacity))


# =============================================================================
#  Solvers for the extended RBM system
#
#  Three interchangeable ways of getting the densities and (U, Omega) out of the
#  system built above.  They all take the same right-hand side and return
#  (solution, residual norm), so they can be swapped freely:
#
#    solve_dense_lstsq   least squares, the historical default
#    solve_dense_direct  jnp.linalg.solve -- E is square, so this is legal
#    solve_schur         block elimination of the static (wall + obstacle) group
#
#  solve_schur is the one aimed at time evolution: only the swimmers move, so
#  Eww is identical at every step and its factorization can be built once with
#  factor_static_block and handed back in on every subsequent solve.  The
#  coupling blocks Ewp/Epw/Epp still have to be rebuilt each step because they
#  depend on the swimmer positions.
# =============================================================================

def solve_dense_lstsq(E, rhs, rcond=1e-15):
    """Mode 1: least-squares solve of the full extended system."""
    x = jnp.linalg.lstsq(E, rhs, rcond=rcond)[0]
    return x, jnp.linalg.norm(E @ x - rhs)


def solve_dense_direct(E, rhs):
    """Mode 2: direct square solve of the full extended system."""
    x = jnp.linalg.solve(E, rhs)
    return x, jnp.linalg.norm(E @ x - rhs)


def factor_static_block(Eww, method='pinv', rcond=1e-12):
    """
    Factor the static wall(+obstacle) block for reuse across time steps.

    'pinv' (default) -- dense pseudo-inverse.  The interior-Dirichlet DL wall
    operator -I/2 + D carries the classical rank-one normal-vector nullspace and
    no completion term is added here, so a plain LU of Eww is near-singular.  That
    nullspace generates zero velocity, so dropping it is physically harmless.
    'lu' -- LU factorization, cheaper, use when Eww is known to be well conditioned.
    """
    if method == 'pinv':
        return {'method': 'pinv', 'op': jnp.linalg.pinv(Eww, rcond=rcond)}
    elif method == 'lu':
        return {'method': 'lu', 'op': jax.scipy.linalg.lu_factor(Eww)}
    raise ValueError(f"unknown static factorization method '{method}'")


def apply_static_inverse(fac, B):
    """Apply the factorization from factor_static_block to a vector or matrix."""
    if fac['method'] == 'pinv':
        return fac['op'] @ B
    return jax.scipy.linalg.lu_solve(fac['op'], B)


def solve_schur(blocks, rhs, static_fac=None, method='pinv', rcond=1e-15):
    """
    Mode 3: solve E x = rhs by eliminating the static group.

    With E = [[Eww, Ewp], [Epw, Epp]] and rhs = [b_w; b_p],

        x_w = Eww^-1 (b_w - Ewp x_p),   (Epp - Epw Eww^-1 Ewp) x_p = b_p - Epw Eww^-1 b_w

    `blocks` is the dict returned by rbm / rbm_obs / rbm_wrapper; the split point is
    read off Eww, so no slicing of E is needed (E need not be formed at all).

    Pass `static_fac` from a previous call to skip refactoring Eww -- that is the
    point of the whole exercise for time stepping.  Returns (x, resid, static_fac).
    """
    Eww = blocks['Eww']; Ewp = blocks['Ewp']
    Epw = blocks['Epw']; Epp = blocks['Epp']
    n_stat = Eww.shape[0]
    b_w = rhs[:n_stat]
    b_p = rhs[n_stat:]

    if static_fac is None:
        static_fac = factor_static_block(Eww, method=method)

    X = apply_static_inverse(static_fac, Ewp)   # Eww^-1 Ewp
    y = apply_static_inverse(static_fac, b_w)   # Eww^-1 b_w

    S = Epp - Epw @ X
    x_p = jnp.linalg.lstsq(S, b_p - Epw @ y, rcond=rcond)[0]
    x_w = y - X @ x_p
    x = jnp.concatenate([x_w, x_p])

    resid = jnp.linalg.norm(jnp.concatenate([Eww @ x_w + Ewp @ x_p - b_w,
                                             Epw @ x_w + Epp @ x_p - b_p]))
    return x, resid, static_fac


def solve_rbm_system(E, blocks, rhs, mode=1, static_fac=None, rcond=1e-15):
    """
    Dispatch on the solver mode: 1 = lstsq, 2 = direct solve, 3 = Schur complement.
    Returns (x, resid, static_fac); static_fac is None except in mode 3.
    """
    if mode == 1:
        x, resid = solve_dense_lstsq(E, rhs, rcond=rcond)
        return x, resid, None
    elif mode == 2:
        x, resid = solve_dense_direct(E, rhs)
        return x, resid, None
    elif mode == 3:
        return solve_schur(blocks, rhs, static_fac=static_fac, rcond=rcond)
    raise ValueError(f"unknown solver mode {mode}, expected 1, 2 or 3")


# =============================================================================
#  Block-Jacobi (self-interaction) preconditioner
#
#  E is second kind, so its iteration count is mesh independent -- but it is not
#  *body* independent: with no preconditioner GMRES needs roughly 24 iterations for
#  the wall plus swimmer alone and ~13 more per added obstacle, because the operator
#  is only "identity plus compact" one body at a time and the body-body coupling
#  blocks are what Krylov has to resolve.  Two things follow from the spectrum:
#
#    * The jump terms are -I/2 on the wall rows and +I/2 on the body rows, so the
#      eigenvalues of the raw E cluster around +1/2 AND -1/2 -- straddling the
#      origin, which is the worst case for GMRES.  Simply scaling the wall rows by
#      -2 and the body rows by +2 moves the cluster to 1 and already buys ~1.4x.
#    * Inverting each body's own diagonal block does that and removes the
#      self-interaction as well, leaving only the coupling: median |1 - lambda| drops
#      from 0.50 to 3e-15 (90th percentile 2.7e-4) and the iteration count falls by
#      ~2.4x (76 -> 32 at the 4-obstacle course geometry, 24 -> 9 with no obstacles).
#
#  The diagonal blocks are the *self* quadrature only -- no close evaluation -- so
#  building and factoring them costs about half a matvec: 7.7 ms at n = 1363 against
#  ~55 ms for a full rbm_wrapper assembly and ~15 ms for a single matvec.  The wall and obstacle blocks carry no active-particle
#  geometry, exactly like rbm_static_block, so a time loop factors them once and
#  passes them back in via `static_pc=`.
#
#  Note the row order the layout fixes: force and torque rows are grouped by *type*
#  after all the density rows, not by particle, so a particle's diagonal block is not
#  a contiguous slice of E once there is more than one particle.  The blocks below
#  therefore carry explicit row/column index arrays rather than slices.
# =============================================================================

@jit
def _pc_block_wall(s, mu):
    """
    Wall diagonal block: the interior-Dirichlet DL with its -I/2 jump, plus the
    classical rank-one completion n(x) * int sigma.n ds.

    The completion is here for the preconditioner only -- E itself is left alone, and
    a preconditioner is free to differ from the block it approximates.  Without it the
    block is singular and any inverse of it (pseudo- or otherwise) annihilates the
    wall-DL nullspace, so M can never produce the component of the solution that lies
    along it.  With obstacles present the swimmer-obstacle coupling feeds that
    direction back and GMRES still converges, but on an empty container the wall block
    is the only thing acting on those unknowns and preconditioned GMRES stalls
    outright -- 2349 iterations to a 6.7e-9 residual against 32 unpreconditioned.
    The completion removes the nullspace (cond 1e17 -> 1e3), costs one outer product,
    and leaves the block LU-factorable.
    """
    A, _, _ = StoDLP(s, s, mu, jnp.array([]), self=True, near=False, panel=True, need_T=False)
    A = -jnp.eye(2 * s['x'].size) / 2. + A
    nx = s['nx']
    nvec = jnp.concatenate([jnp.real(nx), jnp.imag(nx)])              # the null direction
    wvec = jnp.concatenate([jnp.real(nx) * s['ws'], jnp.imag(nx) * s['ws']])  # int (.) n ds
    return A + jnp.outer(nvec, wvec)


@jit
def _pc_block_body(v, mu):
    """Passive-body diagonal block: exterior SL+DL self quadrature with its +I/2 jump."""
    u, _ = pair_block(v, v, True, mu, need_T=False)
    return jnp.eye(u.shape[0]) / 2. + u


@jit
def _pc_block_ptcl(v, mu):
    """
    Active-particle diagonal block, extended by that particle's own (Ux, Uy, Omega)
    columns and its own force/torque rows -- the (2N+3) x (2N+3) piece of E built from
    body `v` alone.  Mirrors rbm / rbm_obs term for term: the velocity rows get
    +I/2 + (S+D)_self and the bc_sqr rigid-motion columns, and the load rows integrate
    the self traction fMat_ptcl = -(-I/2 + T_self) against ws and (-dy, dx) * ws.
    """
    u, T = pair_block(v, v, True, mu, need_T=True)
    n = v['x'].size
    A22 = jnp.eye(2 * n) / 2. + u
    rel = v['x'] - jnp.mean(v['x'])
    dx, dy = jnp.real(rel), jnp.imag(rel)
    ws = v['ws']

    bc = jnp.zeros((2 * n, 3))
    bc = bc.at[:n, 0].set(-1.0)
    bc = bc.at[n:, 1].set(-1.0)
    bc = bc.at[:n, 2].set(-dy)
    bc = bc.at[n:, 2].set(dx)

    fMat = -(-jnp.eye(2 * n) / 2. + T)
    z = jnp.zeros_like(ws)[None, :]
    intF = jnp.block([[ws[None, :], z], [z, ws[None, :]]])
    intT = jnp.concatenate([(-dy * ws)[None, :], (dx * ws)[None, :]], axis=1)

    return jnp.block([[A22,        bc            ],
                      [intF @ fMat, jnp.zeros((2, 3))],
                      [intT @ fMat, jnp.zeros((1, 3))]])


def rbm_block_jacobi(s, obs_cell, ptcl_cell, mu, static_pc=None):
    """
    Factor the self-interaction diagonal blocks of the confined RBM operator.

    Returns a dict with 'blocks' -- a list of (row_idx, col_idx, lu_factor) triples in
    E's own index space -- plus 'n' and 'static' (the wall+obstacle part on its own,
    ready to hand back in as `static_pc` on a later step, since nothing in it depends
    on where the swimmers are).

    Every block is LU-factored.  The wall block is only invertible because
    _pc_block_wall adds the rank-one completion to it; see there for why a
    pseudo-inverse of the uncompleted block is not a workable substitute.
    """
    lay = rbm_dof_layout(s, obs_cell, ptcl_cell)
    n_bod = len(lay['ptcl_sizes'])
    off_uom = lay['off_uom']

    if static_pc is None:
        static = []
        idx = np.arange(lay['n_wall'])
        static.append((idx, idx, sla.lu_factor(np.asarray(_pc_block_wall(s, mu)))))
        off = lay['off_obs']
        for k, sz in lay['obs_sizes']:
            idx = np.arange(off, off + sz)
            static.append((idx, idx, sla.lu_factor(np.asarray(_pc_block_body(obs_cell[k], mu)))))
            off += sz
    else:
        static = static_pc

    blocks = list(static)
    off = lay['off_ptcl']
    for i, (k, sz) in enumerate(lay['ptcl_sizes']):
        rows = np.concatenate([np.arange(off, off + sz),
                               [off_uom + 2 * i, off_uom + 2 * i + 1],
                               [off_uom + 2 * n_bod + i]])
        cols = np.concatenate([np.arange(off, off + sz),
                               [off_uom + 3 * i, off_uom + 3 * i + 1, off_uom + 3 * i + 2]])
        blocks.append((rows, cols, sla.lu_factor(np.asarray(_pc_block_ptcl(ptcl_cell[k], mu)))))
        off += sz

    return {'blocks': blocks, 'n': lay['n_total'], 'static': static}


def make_rbm_preconditioner(pc):
    """Wrap a rbm_block_jacobi result as a scipy LinearOperator for GMRES's M=."""
    n = pc['n']
    blocks = pc['blocks']

    def apply(v):
        out = np.zeros(n, dtype=np.float64)
        v = np.asarray(v, dtype=np.float64).ravel()
        for rows, cols, fac in blocks:
            # M approximates E, so the block maps residual entries on `rows` to
            # unknowns on `cols`.
            out[cols] = sla.lu_solve(fac, v[rows])
        return out

    return spla.LinearOperator((n, n), matvec=apply, dtype=np.float64)


# =============================================================================
#  Matrix-free GMRES solve
#
#  Deliberately kept out of solve_rbm_system: that function dispatches between
#  three factorizations of an *assembled* E, while this one never forms E at all.
#  It drives rbm_matvec_flat through a scipy LinearOperator.
#
#  A note on conditioning.  E is numerically singular -- the interior-Dirichlet DL
#  wall operator carries the classical rank-one normal-vector nullspace, so
#  cond(E) ~ 1e17 -- but the right-hand side is consistent and that nullspace
#  generates no flow, so GMRES converges without any completion term.  The density it
#  returns can differ from the dense solution by a multiple of that nullspace;
#  U/Omega and the evaluated velocity field are the quantities that must agree, and
#  they do.
#
#  That conditioning is also a red herring for convergence *speed*, and it is worth
#  recording why so nobody chases it again.  Adding the standard rank-one completion
#  n(x) * int sigma.n ds to the wall block takes cond(E) from 1e17 to 1e3 and changes
#  the iteration count by one (76 -> 77 at the 4-obstacle geometry).  What actually
#  sets the iteration count is where the eigenvalues sit, and they sit at +-1/2 with
#  a long tail from the body-body coupling -- which is what rbm_block_jacobi above
#  fixes, and why it is on by default below.
# =============================================================================

def make_rbm_linear_operator(s, obs_cell, ptcl_cell, mu, warmup=True, split=None):
    """
    Wrap rbm_matvec_flat for this geometry as a scipy LinearOperator.

    Returns (op, fn, layout).  `fn` is the jax-in/jax-out apply, useful for timing a
    bare matvec or for checking against a dense E; `layout` is the rbm_dof_layout dict.
    With warmup=True the operator is traced and compiled before returning, so nothing
    timed afterwards includes compilation.

    `fn` closes over the *module-level* jitted rbm_matvec_flat rather than wrapping a
    fresh lambda in jit here.  A fresh lambda is a new callable with its own empty cache,
    so every operator built for a new swimmer pose would retrace and recompile the whole
    operator -- which is exactly what a time loop does.  Going through the shared jit
    keeps one cache entry per discretization, and the geometry dicts are pytree arguments
    whose shapes do not change as a body moves, so later poses hit it.
    """
    layout = rbm_dof_layout(s, obs_cell, ptcl_cell)
    n = layout['n_total']
    def fn(x):
        return rbm_matvec_flat(x, s, obs_cell, ptcl_cell, mu, split=split)
    if warmup:
        fn(jnp.zeros((n,))).block_until_ready()

    def mv(v):
        # np.asarray on a jax array returns a read-only view, and scipy's gmres
        # writes into the vector it gets back -- so copy on the way out.
        return np.array(fn(jnp.asarray(np.asarray(v, dtype=np.float64).ravel())),
                        dtype=np.float64, copy=True)

    return spla.LinearOperator((n, n), matvec=mv, dtype=np.float64), fn, layout


def solve_gmres_matvec(s, obs_cell, ptcl_cell, mu, rhs, rtol=1e-10, atol=0.0,
                       restart=200, maxiter=20, x0=None, op=None, warmup=True,
                       precond=True, pc=None, split=None):
    """
    Solve the extended RBM system with GMRES on the matrix-free operator.

    Interchangeable with solve_rbm_system as far as the answer goes, but takes the
    geometry instead of an assembled E.  Pass a prebuilt `op` from
    make_rbm_linear_operator to reuse a compiled apply across solves (and to keep
    compilation out of a timing loop).

    Preconditioning is on by default: `precond=True` builds the block-Jacobi
    self-interaction preconditioner (see rbm_block_jacobi) for this geometry, which
    costs about one matvec to build and cuts the iteration count by ~2.4x.  Pass a
    prebuilt `pc` from rbm_block_jacobi to reuse it -- in a time loop, build one with
    `static_pc=` carried over so only the swimmer block is refactored.  `precond=False`
    reproduces the old unpreconditioned behaviour.

    rtol defaults to 1e-10 rather than 1e-12: the matvec itself only reproduces E to a
    ~1e-11 backward error (see the two traction routes in stoDLP_closeglobal), so the
    last two digits cost ~10% more iterations without buying accuracy.

    Returns (x, resid, info, n_iter, op) with x a jax array, resid = ||A x - rhs||
    measured with the same matvec, and info the scipy convergence flag (0 = success).
    """
    if op is None:
        op, _, _ = make_rbm_linear_operator(s, obs_cell, ptcl_cell, mu, warmup=warmup, split=split)
    b = np.asarray(rhs, dtype=np.float64).ravel()

    M = None
    if precond:
        if pc is None:
            pc = rbm_block_jacobi(s, obs_cell, ptcl_cell, mu)
        M = make_rbm_preconditioner(pc)

    n_iter = [0]
    def _count(_):
        n_iter[0] += 1

    x, info = spla.gmres(op, b, M=M,
                         x0=None if x0 is None else np.asarray(x0, dtype=np.float64).ravel(),
                         rtol=rtol, atol=atol, restart=restart, maxiter=maxiter,
                         callback=_count, callback_type='pr_norm')
    resid = float(np.linalg.norm(op.matvec(x) - b))
    return jnp.asarray(x), resid, info, n_iter[0], op
